# ============================================
# $Id: Makefile,v 1.3 2006/06/19 15:29:06 eric Exp $
# ============================================


SUBDIR= mime
include $(utildir)/PubRule
DISTFILES = $(SUBDIR) Makefile

