# ============================================
# $Id: Makefile,v 1.4 2006/06/20 08:00:38 eric Exp $
# ============================================


SUBDIR= mime
include $(utildir)/PubRule
DISTFILES += $(SUBDIR) Makefile

