# ============================================
# $Id: Makefile,v 1.5 2008/02/08 08:09:50 eric Exp $
# ============================================


#SUBDIR= mime
include $(utildir)/PubRule
DISTFILES += $(SUBDIR) Makefile

