# ============================================
# $Id: Makefile,v 1.11 2007/11/14 16:56:13 eric Exp $
# ============================================

# get the new appname (basename in uppercase)
appname = WORKSPACEADMIN

export appname


include $(utildir)/PubRule

SUBDIR=  Actions



