# ============================================
# $Id: Makefile,v 1.1 2005/09/13 14:47:16 eric Exp $
# $Log: Makefile,v $
# Revision 1.1  2005/09/13 14:47:16  eric
# *** empty log message ***
#
# Revision 1.1  2001/10/03 08:55:33  eric
# liste des utilisateurs nomade
#
# Revision 1.1  2001/06/13 14:41:44  eric
# contact address book
#
# ============================================


include $(utildir)/PubRule
